apiVersion: v1
kind: ConfigMap
metadata:
  name: jukebox-conf
data:
  conf.yaml: |
    enable_spotify: false
    device_name: ""
    post_init_command: ""
    volume_up_command: ""
    volume_down_command: ""
    trigger_only_mode: false
    tag_mapper_configuration_file: "/mnt/jukebox-audio/tag-mapper.yaml"
    audio_base_directory: "/mnt/jukebox-audio"
    pause_pin: 14
    enable_rfid_controller: true
    debug: false
    audio_output_device: "default:CARD=vc4hdmi0"