apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukebox
  labels:
    app: jukebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jukebox
  template:
    metadata:
      labels:
        app: jukebox
    spec:
      containers:
      - name: jukebox
        image: mtesseract/jukeboxd:latest
        imagePullPolicy: Always
        args: ["/app/bin/jukeboxd-wrapper"]
        securityContext:
          privileged: true
        env:
        - name: RUST_LOG
          value: info 
        volumeMounts:
          - mountPath: /dev/snd
            name: dev-snd
          - mountPath: /run/pulse
            name: pulseaudio-run
          - mountPath: /etc/alsa/conf.d/99-pulseaudio-default.conf
            name: alsa-etc
          - mountPath: /etc/pulse
            name: pulseaudio-etc
          - mountPath: /etc/jukebox
            name: jukebox-conf
          - mountPath: /mnt/jukebox-audio
            name: jukebox-audio
      volumes:
        - name: dev-snd
          hostPath:
            path: /dev/snd
        - name: alsa-etc
          hostPath:
            path: /etc/alsa/conf.d/99-pulseaudio-default.conf.example
        - name: pulseaudio-etc
          hostPath:
            path: /etc/pulse
        - name: pulseaudio-run
          hostPath:
            path: /run/pulse
        - name: jukebox-audio
          persistentVolumeClaim:
            claimName: jukebox-audio
        - name: jukebox-conf
          configMap:
            name: jukebox-conf
