apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukeboxd
  namespace: koffer
  labels:
    app: jukeboxd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jukeboxd
  template:
    metadata:
      labels:
        app: jukeboxd
    spec:
      # initContainers:
      # - name: init
      #   image: alpine:3.16.9
      #   command:
      #     - sh
      #     - -c
      #     - "rm -f /var/run/jukeboxd/hotloading/*"
      #   volumeMounts:
      #     - mountPath: /var/run/jukeboxd
      #       name: var-run-jukeboxd
      containers:
      - name: jukeboxd 
        image: mtesseract/jukeboxd:latest
        imagePullPolicy: Always
        args: ["/app/bin/jukeboxd-wrapper"]
        securityContext:
          privileged: true
        env:
        - name: RUST_LOG
          value: info 
        - name: AUDIO_BASE_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: jukeboxd
              key: audio_base_directory
        - name: TAG_MAPPER_CONFIGURATION_FILE
          valueFrom:
            configMapKeyRef:
              name: jukeboxd
              key: tag_mapper_configuration_file
        - name: TRIGGER_ONLY_MODE
          valueFrom:
            configMapKeyRef:
              name: jukeboxd
              key: trigger_only_mode
        # # - name: PAUSE_PIN
        # #   valueFrom:
        # #     configMapKeyRef:
        # #       name: jukeboxd
        #       key: pause_pin
        volumeMounts:
          - mountPath: /run/pulse
            name: pulseaudio-run
          - mountPath: /etc/pulse
            name: pulseaudio-etc
          - mountPath: /mnt/jukebox-drive
            name: jukebox-drive
          - mountPath: /var/run/jukeboxd
            name: var-run-jukeboxd
      volumes:
        - name: pulseaudio-etc
          hostPath:
            path: /etc/pulse
        - name: pulseaudio-run
          hostPath:
            path: /run/pulse
        - name: jukebox-drive
          persistentVolumeClaim:
            claimName: jukebox-drive
        - name: jukebox-hotloading
          persistentVolumeClaim:
            claimName: jukebox-hotloading
        - name: var-run-jukeboxd
          hostPath:
            path: /jukeboxd
            type: Directory
