apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukebox
  labels:
    app: jukebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jukebox
  template:
    metadata:
      labels:
        app: jukebox
    spec:
      # initContainers:
      # - name: init
      #   image: alpine:3.16.9
      #   command:
      #     - sh
      #     - -c
      #     - "rm -f /var/run/jukeboxd/hotloading/*"
      #   volumeMounts:
      #     - mountPath: /var/run/jukeboxd
      #       name: var-run-jukeboxd
      containers:
      - name: jukebox
        image: mtesseract/jukeboxd:latest
        imagePullPolicy: Always
        args: ["/app/bin/jukeboxd-wrapper"]
        securityContext:
          privileged: true
        env:
        - name: RUST_LOG
          value: info 
        volumeMounts:
          - mountPath: /run/pulse
            name: pulseaudio-run
          - mountPath: /etc/pulse
            name: pulseaudio-etc
          - mountPath: /etc/jukebox
            name: jukebox-conf
          - mountPath: /mnt/jukebox-drive/audio
            name: jukebox-drive
      volumes:
        - name: pulseaudio-etc
          hostPath:
            path: /etc/pulse
        - name: pulseaudio-run
          hostPath:
            path: /run/pulse
        - name: jukebox-audio
          persistentVolumeClaim:
            claimName: jukebox-drive
        - name: jukebox-hotloading
          persistentVolumeClaim:
            claimName: jukebox-hotloading
