apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jukebox-hotloading
  namespace: koffer
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 50Mi
