apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jukebox-audio
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
