apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukebox
  labels:
    app: jukebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jukebox
  template:
    metadata:
      labels:
        app: jukebox
    spec:
      containers:
      - name: jukebox
        image: mtesseract/jukeboxd:latest
        imagePullPolicy: Always
        args: ["/app/bin/jukeboxd-wrapper"]
        securityContext:
          privileged: true
        env:
        - name: RUST_LOG
          value: info 
        - name: AUDIO_BASE_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: jukebox-conf
              key: audio_base_directory
        - name: TAG_MAPPER_CONFIGURATION_FILE
          valueFrom:
            configMapKeyRef:
              name: jukebox-conf
              key: tag_mapper_configuration_file
        - name: ENABLE_SPOTIFY
          valueFrom:
            configMapKeyRef:
              name: jukebox-conf
              key: enable_spotify
        - name: TRIGGER_ONLY_MODE
          valueFrom:
            configMapKeyRef:
              name: jukebox-conf
              key: trigger_only_mode
        - name: ENABLE_RFID_CONTROLLER
          valueFrom:
            configMapKeyRef:
              name: jukebox-conf
              key: enable_rfid_controller
        # # - name: PAUSE_PIN
        # #   valueFrom:
        # #     configMapKeyRef:
        # #       name: jukebox-conf
        #       key: pause_pin
        volumeMounts:
          - mountPath: /run/pulse
            name: pulseaudio-run
          - mountPath: /etc/pulse
            name: pulseaudio-etc
          - mountPath: /etc/jukebox
            name: jukebox-conf
          - mountPath: /mnt/jukebox-drive/audio
            name: jukebox-audio
      volumes:
        - name: pulseaudio-etc
          hostPath:
            path: /etc/pulse
        - name: pulseaudio-run
          hostPath:
            path: /run/pulse
        - name: jukebox-audio
          persistentVolumeClaim:
            claimName: jukebox-audio
        - name: jukebox-conf
          configMap:
            name: jukebox-conf
